name: Lint Guard Keys

on:
  push:
    paths:
      - "MIND/language/sequences/**/*.flow.jsonld"
      - "MIND/language/sequences/.lint/guardkeys.yaml"
      - "tools/lint/**"
  pull_request:
    paths:
      - "MIND/language/sequences/**/*.flow.jsonld"
      - "MIND/language/sequences/.lint/guardkeys.yaml"
      - "tools/lint/**"

jobs:
  guardkeys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/lint/requirements.txt

      - name: Run Guard Keys Linter
        run: |
          python tools/lint/guardkeys_lint.py \
            --config MIND/language/sequences/.lint/guardkeys.yaml \
            --globs "MIND/language/sequences/**/*.flow.jsonld"
