# .github/workflows/mandala-validate.yml
name: Mandala Validate
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install ruamel.yaml jsonschema
      - name: Paths & schema
       - name: Validate behavior_hooks against schema (v1)
  run: |
    python - <<'PY'
    import os, sys, yaml
    from jsonschema import Draft7Validator
    schema_path = "plating/schemas/mandala.behavior_hook.v1.yml"
    with open(schema_path, encoding="utf-8") as f:
        schema = yaml.safe_load(f)
    validator = Draft7Validator(schema)
    errs = []
    for root, _, files in os.walk("MIND/identity/proxies"):
        for fn in files:
            if fn.endswith(".yaml") and "/behavior_hooks/" in os.path.join(root, fn).replace("\\","/"):
                p = os.path.join(root, fn)
                try:
                    data = yaml.safe_load(open(p, encoding="utf-8"))
                except Exception as e:
                    errs.append(f"{p}: YAML parse error: {e}")
                    continue
                for e in validator.iter_errors(data):
                    errs.append(f"{p}: {e.message}")
    if errs:
        print("\n".join(errs))
        sys.exit(1)
    print("behavior_hooks OK")
    PY
