id: abb://combo-kissdrop/kissdrop@1.0
name: Kissdrop
goal: Dissolve intensity into intimacy
glyphs:
  triggers: []
  combos: ["Kissdrop"]
triggers: ["overheat", "escalation"]
state:
  start: placeholder
  steps:
    - name: placeholder
      do: "TODO — define melt sequence"
      exit: true
exits: ["intimacy established", "tension softened"]
constraints: {pace: [slow, steady], valence: [warm]}
telemetry: {signals: [ease, depth, engage, overheat, stall]}
compatibility: {prefers: [Sophie, Susanna], forbids: []}
version: "0.1"
